name: Build CPython 3.12.x for Alpine armv7l (Soft-Float) to /mnt/us

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build-cpython:
    runs-on: ubuntu-latest # 使用 Ubuntu 运行器

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for ARMv7l emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm # 启用 ARM 平台支持，包括 armv7l

      - name: Download CPython 3.12.0 Source # 注意：这里使用3.12.0作为示例，您可以替换为3.12.x的任何具体版本
        run: |
          wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
          tar -xf Python-3.12.0.tgz
          mv Python-3.12.0 cpython-source

      - name: Build CPython in Alpine ARMv7l Docker Container
        run: |
          # 运行一个 arm32v7/alpine 容器，并将当前目录挂载到容器的 /workspace
          # 在容器内执行编译和安装步骤
          # 关键更改：添加 --platform linux/arm/v7
          docker run --rm --platform linux/arm/v7 \
            -v "$(pwd):/workspace" \
            arm32v7/alpine:latest /bin/sh -c "
            apk update && \
            apk add --no-cache \
              build-base \
              linux-headers \
              openssl-dev \
              sqlite-dev \
              zlib-dev \
              bzip2-dev \
              readline-dev \
              ncurses-dev \
              gdbm-dev \
              libffi-dev \
              expat-dev \
              tar \
              wget && \
            
            cd /workspace/cpython-source && \
            
            # 配置 CPython
            # --prefix=/mnt/us: 设置安装目录为 /mnt/us
            # --enable-optimizations: 启用优化编译
            # --with-ensurepip=install: 确保安装 pip
            # 注意：--host 参数已更改为 armv7l-alpine-linux-musleabi 以支持软浮点
            ./configure --host=armv7l-alpine-linux-musleabi --build=x86_64-linux-gnu --prefix=/mnt/us --enable-optimizations --with-ensurepip=install && \
            
            # 编译
            make -j$(nproc) && \
            
            # 安装
            make install && \
            
            # 打包结果
            # 注意：cd /mnt/us 确保打包的是安装目录的内容
            cd /mnt/us && \
            tar -czvf /workspace/cpython-3.12.0-alpine-armv7l-softfloat-mnt-us.tar.gz .
            "

      - name: Upload CPython Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpython-3.12.0-alpine-armv7l-softfloat-mnt-us
          path: cpython-3.12.0-alpine-armv7l-softfloat-mnt-us.tar.gz
